import { expect, type Page } from "@playwright/test";

export type TypstShapeSeed = {
  id?: string;
  left?: number;
  top?: number;
  width?: number;
  height?: number;
  rotation?: number;
  fillColor?: string | null;
  altTextTitle?: string;
  altTextDescription?: string;
  name?: string;
  tags?: Record<string, string>;
  typstSource?: { preamble: string; body: string };
  svgContent?: string;
};

export type OfficeMockSeed = {
  slides?: { id?: string; shapes?: TypstShapeSeed[] }[];
  selectedSlideIds?: string[];
  selectedShapeIds?: string[];
  slideWidth?: number;
  slideHeight?: number;
};

export type ShapeSnapshot = {
  id: string;
  left: number;
  top: number;
  width: number;
  height: number;
  rotation: number;
  altTextTitle: string;
  altTextDescription: string;
  name: string;
  fillColor: string | null;
  tags: Record<string, string>;
  customXml: string[];
  svgContent: string | null;
};

export type OfficeSnapshot = {
  selectedSlideIds: string[];
  selectedShapeIds: string[];
  insertedSvgCalls: { slideId: string | null; svg: string }[];
  slides: { id: string; shapes: ShapeSnapshot[] }[];
};

type OfficeMockWindow = Window & typeof globalThis & {
  __pptypstOfficeSeed?: OfficeMockSeed;
  __pptypstOfficeMock: {
    reset: (_seed?: OfficeMockSeed) => void;
    selectShapes: (_slideId: string, _shapeIds: string[]) => Promise<void>;
    clearSelection: (_slideId?: string) => Promise<void>;
    snapshot: () => OfficeSnapshot;
  };
};

export const typstShapeTags = {
  kind: "TypstKind",
  fontSize: "TypstFontSize",
  fillColor: "TypstFillColor",
  mathMode: "TypstMathMode",
} as const;

export const typstShapeMetadata = {
  name: "Typst Shape",
  altTextTitle: "PPTypst shape",
  altTextDescription: "Generated by PPTypst. Edit this shape with the PPTypst add-in.",
} as const;

/** Page object for the PPTypst PowerPoint task pane. */
export class PowerPointPage {
  private readonly page: Page;

  constructor(page: Page) {
    this.page = page;
  }

  /** Opens the task pane and waits until the add-in has finished its initial setup. */
  async goto() {
    await this.page.goto("powerpoint.html");
    await expect(this.page.locator("#insertBtn")).toContainText(
      /Insert|Update/,
    );
  }

  /** Seeds the browser Office mock and reloads the task pane around that model. */
  async gotoWithOffice(seed: OfficeMockSeed) {
    await this.page.addInitScript((officeSeed) => {
      window.localStorage.clear();
      const officeWindow = window as OfficeMockWindow;
      officeWindow.__pptypstOfficeSeed = officeSeed;
    }, seed);
    await this.goto();
  }

  /** Types a Typst expression into the editor, triggering the preview update. */
  async previewExpression(expression: string) {
    await this.page.locator("#typstInput").fill(expression);
  }

  async setPreamble(preamble: string) {
    if (!(await this.page.locator("#preambleInput").isVisible())) {
      await this.page.locator("#preambleSummary").click();
    }
    await this.page.locator("#preambleInput").fill(preamble);
  }

  async setFontSize(fontSize: string) {
    await this.page.locator("#fontSize").fill(fontSize);
  }

  async setFillColor(fillColor: string | null) {
    const fillEnabled = this.page.locator("#fillColorEnabled");
    if (fillColor === null) {
      await fillEnabled.setChecked(false);
      return;
    }

    await fillEnabled.setChecked(true);
    await this.page.locator("#fillColor").fill(fillColor);
  }

  async insertOrUpdate() {
    await this.page.locator("#insertBtn").click();
  }

  async bulkUpdateFontSize() {
    await this.page.locator("#bulkUpdateBtn").click();
  }

  async selectShapes(slideId: string, shapeIds: string[]) {
    await this.page.evaluate(
      async ({ selectedSlideId, selectedShapeIds }) => {
        const officeWindow = window as OfficeMockWindow;
        await officeWindow.__pptypstOfficeMock.selectShapes(
          selectedSlideId,
          selectedShapeIds,
        );
      },
      { selectedSlideId: slideId, selectedShapeIds: shapeIds },
    );
  }

  async clearSelection(slideId?: string) {
    await this.page.evaluate(async (selectedSlideId) => {
      const officeWindow = window as OfficeMockWindow;
      await officeWindow.__pptypstOfficeMock.clearSelection(selectedSlideId);
    }, slideId);
  }

  async snapshot(): Promise<OfficeSnapshot> {
    return this.page.evaluate(() => {
      const officeWindow = window as OfficeMockWindow;
      return officeWindow.__pptypstOfficeMock.snapshot();
    });
  }

  async expectStatus(message: string) {
    await expect(this.page.locator("#status")).toHaveText(message);
  }

  async expectInsertMode() {
    await expect(this.page.locator("#insertBtn")).toContainText("Insert");
  }

  async expectUpdateMode() {
    await expect(this.page.locator("#insertBtn")).toContainText("Update");
  }

  async expectBulkUpdateVisible() {
    await expect(this.page.locator("#bulkUpdateBtn")).toBeVisible();
  }

  async expectTypstCode(code: string) {
    await expect(this.page.locator("#typstInput")).toHaveValue(code);
  }

  async expectPreamble(preamble: string) {
    await expect(this.page.locator("#preambleInput")).toHaveValue(preamble);
  }

  async expectFontSize(fontSize: string) {
    await expect(this.page.locator("#fontSize")).toHaveValue(fontSize);
  }

  async expectFillColor(fillColor: string | null) {
    if (fillColor === null) {
      await expect(this.page.locator("#fillColorEnabled")).not.toBeChecked();
      return;
    }

    await expect(this.page.locator("#fillColorEnabled")).toBeChecked();
    await expect(this.page.locator("#fillColor")).toHaveValue(fillColor);
  }

  /** Asserts that the preview pane contains a rendered SVG. */
  async expectPreviewVisible() {
    await expect(this.page.locator("#previewContent svg")).toBeVisible();
  }

  /** Reloads the task pane and waits for the add-in to finish initializing. */
  async reload() {
    await this.page.reload();
    await expect(this.page.locator("#insertBtn")).toContainText(/Insert|Update/);
  }

  /** Opens the collapsible Custom fonts panel if it is currently closed. */
  async openFontsPanel() {
    const isOpen = await this.page.locator("#fontsDetails").evaluate(
      element => (element as HTMLDetailsElement).open,
    );
    if (!isOpen) {
      await this.page.locator("#fontsDetails summary").click();
    }
  }

  /** Uploads one or more font files into the Custom fonts panel. */
  async addFontFiles(files: { name: string; buffer: Buffer }[]) {
    await this.page.locator("#fontsInput").setInputFiles(
      files.map(file => ({ name: file.name, mimeType: "font/ttf", buffer: file.buffer })),
    );
  }

  /** Removes the first listed custom font via its remove button. */
  async removeFirstFont() {
    await this.page.locator(".fonts-item-remove").first().click();
  }

  /** Locator for the listed custom-font rows. */
  fontItems() {
    return this.page.locator(".fonts-item");
  }

  /** Asserts how many listed fonts report the given family name. */
  async expectFontFamilyCount(family: string, count: number) {
    await expect(
      this.page.locator(".fonts-item-family", { hasText: family }),
    ).toHaveCount(count);
  }

  /** Asserts that exactly one listed font shows the given style badge. */
  async expectFontStyleListed(style: string) {
    await expect(
      this.page.locator(".fonts-item-style", { hasText: style }),
    ).toHaveCount(1);
  }

  /** Asserts that no custom fonts are listed. */
  async expectNoCustomFonts() {
    await expect(this.page.locator(".fonts-empty")).toBeVisible();
  }
}
