/**
 * Application-wide constants
 */

/**
 * PowerPoint shape configuration.
 */
export const SHAPE_CONFIG = {
  NAME: "Typst Shape",
  ALT_TEXT_TITLE: "PPTypst shape",
  ALT_TEXT_DESCRIPTION: "Generated by PPTypst. Edit this shape with the PPTypst add-in.",
  TAGS: {
    KIND: "TypstKind",
    FONT_SIZE: "TypstFontSize",
    FILL_COLOR: "TypstFillColor",
    MATH_MODE: "TypstMathMode",
  },
  TAG_VALUES: {
    KIND: "typst",
  },
  CUSTOM_XML: {
    NAMESPACE: "https://splines.github.io/pptypst/shape/v1",
    ROOT: "pptypst:content",
    PREAMBLE_NODE: "pptypst:preamble",
    BODY_NODE: "pptypst:body",
  },
} as const;

/**
 * Special values for fill color.
 */
export const FILL_COLOR_DISABLED = "disabled";

/**
 * DOM element IDs used in the UI.
 */
export const DOM_IDS = {
  STATUS: "status",
  FONT_SIZE: "fontSize",
  FILL_COLOR_ENABLED: "fillColorEnabled",
  FILL_COLOR: "fillColor",
  PREVIEW_FILL_ENABLED: "previewFillEnabled",
  MATH_MODE_ENABLED: "mathModeEnabled",
  PREAMBLE_DETAILS: "preambleDetails",
  PREAMBLE_SUMMARY: "preambleSummary",
  PREAMBLE_INPUT: "preambleInput",
  INPUT_WRAPPER: "inputWrapper",
  TYPST_INPUT: "typstInput",
  INSERT_BTN: "insertBtn",
  BULK_UPDATE_BTN: "bulkUpdateBtn",
  PREVIEW_CONTENT: "previewContent",
  DARK_MODE_TOGGLE: "darkModeToggle",
  DIAGNOSTICS_CONTAINER: "diagnosticsContainer",
  DIAGNOSTICS_CONTENT: "diagnosticsContent",
  FILE_INPUT: "fileInput",
  GENERATE_FROM_FILE_BTN: "generateFromFileBtn",
  FILE_INFO: "fileInfo",
  FILE_NAME: "fileName",
  DROPZONE_LABEL: "dropzoneLabel",
  THEME_TOGGLE_BTN: "themeToggleBtn",
  ABOUT_LINK: "aboutLink",
  ABOUT_MODAL: "aboutModal",
  ABOUT_MODAL_CLOSE: "aboutModalClose",
} as const;

/**
 * LocalStorage keys.
 */
export const STORAGE_KEYS = {
  FONT_SIZE: "typstFontSize",
  FILL_COLOR: "typstFillColor",
  PREVIEW_FILL: "typstPreviewFill",
  MATH_MODE: "typstMathMode",
  PREAMBLE: "typstPreamble",
  PREAMBLE_OPEN: "typstPreambleOpen",
  THEME: "typstTheme",
} as const;

/**
 * SVG processing constants.
 */
export const SVG_CONFIG = {
  PADDING_RATIO: 0.04,
  FALLBACK_WIDTH: 400,
  FALLBACK_HEIGHT: 250,
} as const;

/**
 * Theme values.
 */
export const THEMES = {
  DARK: "dark",
  LIGHT: "light",
} as const;

/**
 * Preview configuration.
 */
export const PREVIEW_CONFIG = {
  MAX_HEIGHT: "320px",
  DARK_MODE_FILL: "#ffffff",
  LIGHT_MODE_FILL: "#000000",
} as const;

/**
 * Button text.
 */
export const BUTTON_TEXT = {
  INSERT: "Insert <kbd>Ctrl+Enter</kbd>",
  UPDATE: "Update <kbd>Ctrl+Enter</kbd>",
  GENERATE_FROM_FILE: "Generate from file",
  UPDATE_FROM_FILE: "Update from file",
} as const;

/**
 * Default values.
 */
export const DEFAULTS = {
  FONT_SIZE: "28",
  FILL_COLOR: "#000000",
  PREAMBLE: "",
} as const;

/**
 * Preamble editor copy.
 */
export const PREAMBLE_UI = {
  GLOBAL_LABEL: "Global preamble",
  SHAPE_LABEL: "Shape preamble",
  MULTI_LABEL: "Preamble",
  GLOBAL_TITLE: "Used for new Typst shapes. Existing shapes keep their own preamble until you update them.",
  SHAPE_TITLE: "This preamble belongs only to the selected shape and is saved when you update it.",
  MULTI_TITLE: "Select a single Typst shape to edit its preamble, or clear the selection to edit the global default.",
} as const;
